version: "3.8"

services:
  apigateway:
    container_name: api_gateway
    ports: 
      - 5000:80
    build:
      context: ../src/ApiGateways/APIGateway
    networks:
      - gateway-net
    depends_on:
      - foodtrackerapi
      - foodtrackerdb

  foodtrackerapi:
    container_name: foodtracker_api
    ports: 
      - 5001:80
    env_file:
      - env/foodtracker_api.env
    build:
      context: ../src/FoodTracker/FoodTracker.API
    networks:
      - foodtrackerservice
      - gateway-net
    depends_on:
      - foodtrackerdb
    
  foodtrackerdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: foodtracker_db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - env/foodtracker_db.env
    networks:
      - foodtrackerservice

  workouttrackerapi:
    container_name: workouttracker_api
    ports:
      - 5002:80
    env_file:
      - env/workouttracker_api.env
    build:
      context: ../src/WorkoutTracker/WorkoutTracker.API
    networks:
      - workouttrackerservice
      - gateway-net
    depends_on:
      - workouttrackerdb

  workouttrackerdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: workouttracker_db
    ports: 
      - 1434:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - env/workouttracker_db.env
    networks:
      - workouttrackerservice
      
networks: 
  workouttrackerservice:
    name: workouttracker_service
  foodtrackerservice:
    name: foodtracker_service
  gateway-net:
    name: gateway_network
  
    