version: "3.8"

services:
  apigateway:
    container_name: api_gateway
    ports: 
      - 5001:80
    build:
      context: ../src/ApiGateways/APIGateway
    networks:
      - gateway-net
    depends_on:
      - foodtrackerapi
      - foodtrackerdb

  foodtrackerapi:
    container_name: foodtracker_api
    ports: 
      - 5000:80
    env_file:
      - env/foodtracker_api.env
    build:
      context: ../src/FoodTracker/FoodTracker.API
    networks:
      - foodtrackerservice
      - gateway-net
    depends_on:
      - foodtrackerdb
    
  foodtrackerdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: foodtracker_db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - env/foodtracker_db.env
    networks:
      - foodtrackerservice
      
networks: 
  foodtrackerservice:
    name: foodtracker_service
  gateway-net:
    name: gateway_network
  
    