version: "3.8"

services:
  apigateway:
    container_name: api_gateway
    ports: 
      - 5001:80
    build:
      context: ../src/ApiGateways/APIGateway
    networks:
      - gateway-net
    depends_on:
      - mealsapi
      - mealsdb

  mealsapi:
    container_name: meals_api
    ports: 
      - 5000:80
    env_file:
      - env/meals_api.env
    build:
      context: ../src/Meals/Meals.API
    networks:
      - mealsservice
      - gateway-net
    depends_on:
      - mealsdb
    
  mealsdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: meals_db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - env/meals_db.env
    networks:
      - mealsservice
      
networks: 
  mealsservice:
    name: meals_service
  gateway-net:
    name: gateway_network
  
    