version: "3.8"

services:
  apigateway:
    container_name: api_gateway
    ports: 
      - 5001:80
    build:
      context: ../src/ApiGateways/APIGateway
    networks:
      - gateway-net
    depends_on:
      - ingredientsapi
      - ingredientsdb

  ingredientsapi:
    container_name: ingredients_api
    ports: 
      - 5000:80
    env_file:
      - env/ingredients_api.env
    build:
      context: ../src/Ingredients/Ingredients.API
    networks:
      - ingredientsservice
      - gateway-net
    depends_on:
      - ingredientsdb
    
  ingredientsdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ingredients_db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
    env_file:
      - env/ingredients_db.env
    networks:
      - ingredientsservice
      
networks: 
  ingredientsservice:
    name: ingredients_service
  gateway-net:
    name: gateway_network
  
    